name: easycalendar
description: A new flutter nepali calendar
version: 0.0.1
homepage: https://github.com/easysoftwareofficial/easy-calendar

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.2
  nepali_utils: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
